# Generated by Django 4.2.5 on 2023-10-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_project_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
