# Generated by Django 4.2.5 on 2023-10-28 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_project_image1_remove_project_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image1',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
        migrations.AddField(
            model_name='project',
            name='image4',
            field=models.FileField(blank=True, null=True, upload_to='media'),
        ),
    ]
