# Generated by Django 4.2.5 on 2023-10-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_project_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image1',
            field=models.FileField(blank=True, default='media/default.jpg', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image2',
            field=models.FileField(blank=True, default='media/default.jpg', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image3',
            field=models.FileField(blank=True, default='media/default.jpg', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image4',
            field=models.FileField(blank=True, default='media/default.jpg', null=True, upload_to='media'),
        ),
    ]
