# Generated by Django 4.2.5 on 2023-10-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_education_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateField(max_length=200),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date',
            field=models.DateField(max_length=200),
        ),
    ]
